<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.aionemu</groupId>
        <artifactId>aion-server</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>game-server</artifactId>
    
    <build>
	    <plugins>
	        <plugin>
	            <groupId>org.apache.maven.plugins</groupId>
	            <artifactId>maven-shade-plugin</artifactId>
	            <version>3.6.0</version>
	            <executions>
	                <execution>
	                    <phase>package</phase>
	                    <goals>
	                        <goal>shade</goal>
	                    </goals>
	                    <configuration>
	                        <createDependencyReducedPom>false</createDependencyReducedPom>
	                        <shadedArtifactAttached>false</shadedArtifactAttached>
	                        <filters>
							    <filter>
							        <artifact>*:*</artifact>
							        <excludes>
							            <exclude>META-INF/MANIFEST.MF</exclude>
							            <exclude>LICENSE</exclude>
							            <exclude>LICENSE.txt</exclude>
							            <exclude>META-INF/LICENSE*</exclude>
							            <exclude>META-INF/NOTICE*</exclude>
							            <exclude>META-INF/*.SF</exclude>
							            <exclude>META-INF/*.DSA</exclude>
							            <exclude>META-INF/*.RSA</exclude>
							            <exclude>module-info.class</exclude>
							        </excludes>
							    </filter>
							</filters>
	                        <transformers>
	                            <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
	                                <mainClass>com.aionemu.gameserver.GameServer</mainClass>
	                                <manifestEntries>
	                                    <Premain-Class>com.aionemu.gameserver.utils.javaagent.JavaAgent</Premain-Class>
	                                    <Can-Redefine-Classes>true</Can-Redefine-Classes>
	                                    <Can-Retransform-Classes>true</Can-Retransform-Classes>
	                                </manifestEntries>
	                            </transformer>
	                        </transformers>
	                    </configuration>
	                </execution>
	            </executions>
	        </plugin>
	    </plugins>
	</build>

    <dependencies>
        <dependency>
            <groupId>com.aionemu</groupId>
            <artifactId>commons</artifactId>
            <version>${project.version}</version>
        </dependency>
        
        <dependency>
		    <groupId>net.sf.trove4j</groupId>
		    <artifactId>trove4j</artifactId>
		    <version>3.0.3</version>
		</dependency>
		
		<dependency>
		    <groupId>joda-time</groupId>
		    <artifactId>joda-time</artifactId>
		    <version>2.12.7</version>
		</dependency>
		
		<dependency>
		    <groupId>com.googlecode.lambdaj</groupId>
		    <artifactId>lambdaj</artifactId>
		    <version>2.3.3</version>
		</dependency>
		
		<dependency>
		    <groupId>com.google.code.findbugs</groupId>
		    <artifactId>jsr305</artifactId>
		    <version>1.3.9</version>
		</dependency>
		
		<dependency>
		    <groupId>javolution</groupId>
		    <artifactId>javolution</artifactId>
		    <version>5.5.1</version>
		</dependency>
    </dependencies>

</project>