//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.04 at 09:59:29 PM EET 
//

package com.aionemu.gameserver.skillengine.condition;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.aionemu.gameserver.model.gameobjects.player.Player;
import com.aionemu.gameserver.network.aion.serverpackets.SM_SYSTEM_MESSAGE;
import com.aionemu.gameserver.skillengine.model.Skill;
import com.aionemu.gameserver.utils.PacketSendUtility;

/**
 * @author ATracer
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrowCheckCondition")
public class ArrowCheckCondition extends Condition {

	@Override
	public boolean validate(Skill skill) {
		if (skill.getEffector() instanceof Player) {
			Player player = (Player)skill.getEffector();
			if (player.isBot())
				// A bot has no client to buy/carry arrows and no owner restocking its quiver, so a
				// Ranger bot with no arrow equipped would otherwise fail every single bow skill outright
				// (not just skip the now-exempted per-shot consumption in Equipment.useArrow()) - this is
				// the earlier gate that decides whether the skill can even be attempted at all. Requested
				// live: "make it do the bow attacks do not use arrow, same as no mana reduction."
				return true;
			if (player.getEquipment().isArrowEquipped())
				return true;

			PacketSendUtility.sendPacket(player, SM_SYSTEM_MESSAGE.STR_CANT_ATTACK_NO_ARROW);
			return false;
		} else {
			return true;
		}
	}
}
